version: '3.8'

services:
  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    networks:
      - kong-network

  kong:
    image: kong:3.0
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-db
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://konga:1337
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on:
      - kong-db
    networks:
      - kong-network

  konga:
    image: pantsel/konga:latest
    container_name: konga
    environment:
      DB_ADAPTER: "postgres"
      DB_HOST: "kong-db"
      DB_USER: "kong"
      DB_PASSWORD: "kong"
      DB_DATABASE: "kong"
      NODE_ENV: "production"
    ports:
      - 1337:1337
    depends_on:
      - kong
      - kong-db
    networks:
      - kong-network

volumes:
  kong-db-data:

networks:
  kong-network:
    driver: bridge
